name: Action - Setup WiX
description: Action to set up WiX paths for candle.exe and light.exe in build environment
runs:
  using: composite
  steps:
    # https://gist.github.com/hibearpanda/d5b5b58bd319132ffd7af606ffa333fc
    #  https://github.com/felixrieseberg/electron-wix-msi/issues/1#issuecomment-674598795
    #  https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path
    #  https://stackoverflow.com/a/64831469
    #  https://github.community/t/set-path-for-wix-toolset-in-windows-runner/154708
    - name: Set WiX paths for candle and light
      shell: powershell
      run: |
        $wixBin = ""
        if (-not [string]::IsNullOrWhiteSpace($env:WIX)) {
          $wixBin = Join-Path -Path $env:WIX -ChildPath "bin"
        }
        if ([string]::IsNullOrWhiteSpace($wixBin) -or -not (Test-Path -Path $wixBin)) {
          $wixBin = "C:\Program Files (x86)\WiX Toolset v3.14\bin"
        }
        if (-not (Test-Path -Path $wixBin)) {
          $wixBin = "C:\Program Files (x86)\WiX Toolset v3.11\bin"
        }
        if (-not (Test-Path -Path $wixBin)) {
          throw "WiX Toolset v3 was not found"
        }
        echo "$wixBin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        $env:Path += ";$wixBin"
        # check that they're found (old way)
        #where.exe candle.exe
        #where.exe light.exe
        # check where they're found, with all information
        Get-Command candle.exe | Format-List
        Get-Command light.exe | Format-List
